title: "Khalid's Portfolio"
author: "Khalid Elhousieny"
email: "khalidrany@hotmail.com"
theme: minima
description: Welcome; this is where you can learn more about me and my work. | You can find my resume on this page, so | go ahead and take a look. I am an aspiring entrepreneur, | and I'm also looking for software engineering opportunities.
